language: go

cache:
  directories:
  - $HOME/.cache/go-build
  - $GOPATH/pkg/mod

os:
  - linux
  - osx

go:
- "1.12"

git:
  depth: 3
  lfs_skip_smudge: true

go_import_path: sigs.k8s.io/kubebuilder

before_install:
- go get -u github.com/golang/dep/cmd/dep
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -sL https://github.com/git-lfs/git-lfs/releases/download/v2.7.2/git-lfs-darwin-amd64-v2.7.2.tar.gz | tar -xz git-lfs; fi

before_script:
 - git lfs install
 - git lfs pull

# Install must be set to prevent default `go get` to run.
# The dependencies have already been vendored by `dep` so
# we don't need to fetch them.
install:
  -

script:
- GO111MODULE=on TRACE=1 ./test.sh
- ./scripts/install_test.sh

# TBD. Suppressing for now.
notifications:
  email: false
